name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '️:arrow_up: Dependencies'
    collapse-after: 3
    labels:
      - dependencies
  - title: ':robot: Automated Commits'
    collapse-after: 3
    labels:
      - tastendruck
      - github_actions
