# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: php-matrix

builds:
  # Hack: Poor man's prebuilt builder.
  - main: ./internal/dummy
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64
    hooks:
      # Overwrite the binary with the prebuilt one, which is what we actually want to release.
      post:
        - cmd: mv "out/{{ .Os }}_{{ .Arch }}/{{ .Name }}" "{{ .Path }}"

nfpms:
  - vendor: Typist Tech Limited
    maintainer: "Typist Tech Limited <opensource+{{ .ProjectName }}@typist.tech>"
    license: MIT
    formats:
      - apk
      - deb
    mtime: "{{ .CommitDate }}"

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

homebrew_casks:
  - name: php-matrix
    homepage: https://github.com/typisttech/php-matrix
    description: |-
      List PHP versions that satisfy the required PHP constraint in composer.json
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/php-matrix"]
          end
    repository:
      owner: typisttech
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_HOMEBREW_GITHUB_TOKEN }}"

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

release:
  use_existing_draft: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
