[env]
GOFLAGS = '-mod=mod'

[tools]
mago = "1.42" # Must be kept in sync with @.github/workflows/lint.yml

[tasks.phar]
depends = ['vendor:no-dev']
run = [
  'box compile',
  'box verify phar/php-matrix',
  'box info phar/php-matrix',
  'php phar/php-matrix --version',
]

[tasks.'test:bin']
env.PATH = '{{ config_root }}/bin:{{ env.PATH }}'
depends = [{ task = 'vendor:no-dev' }]
run = 'go test -count=1 -shuffle=on ./...'

[tasks.'test:phar']
env.PATH = '{{ config_root }}/phar:{{ env.PATH }}'
depends = ['phar']
run = 'go test -count=1 -shuffle=on ./...'

[tasks.gen]
depends = ['gen:test-data', 'gen:data']

[tasks.'gen:data']
depends = ['vendor:no-dev']
run = '{{ config_root }}/bin/generate-data'

[tasks.'gen:test-data']
run = '{{ config_root }}/bin/generate-test-data'

[tasks.'txtar']
depends = ['gen']
run = ['go generate ./...', 'UPDATE_SCRIPTS=1 mise run test:bin']

[tasks.'lint']
depends = ['vendor']
run = [
  'mago analyze',
  'mago lint',
  'composer phpstan -- analyse',
  'mago format --check',
  'mise fmt --check',
]

[tasks.'fix']
depends = ['vendor']
run = [
  'mago analyze --fix',
  'mago lint --fix',
  'composer phpstan -- analyse --fix --quiet || true',
  'mago format',
  'mise fmt',
]

[tasks."vendor"]
run = 'composer install --prefer-dist'

[tasks."vendor:no-dev"]
run = 'composer install --no-dev --prefer-dist'
