name: Format

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  php:
    uses: typisttech/.github/.github/workflows/format-php.yml@v3
    with:
      pint-extra-paths: bin/*
    secrets: inherit
