name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-drafter:
    uses: typisttech/.github/.github/workflows/release-drafter.yml@v2
    permissions:
      contents: write
      pull-requests: read
