name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: read

jobs:
  release-drafter:
    uses: typisttech/.github/.github/workflows/release-drafter.yml@d16ec3549bdab47d10e9863e52ac148e5edd348e
