name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: read

jobs:
  release-drafter:
    uses: typisttech/.github/.github/workflows/release-drafter.yml@f421090f96b7e7a728b6286546e314d383b46e6e
