name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: read

jobs:
  release-drafter:
    uses: typisttech/.github/.github/workflows/release-drafter.yml@d8e6912bb9b5b5050af3dc7fe18bafc68cac626c
