name: Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: 13 3 * * 1 # Weekly on Monday
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - .gitattributes
      - .gitignore
      - LICENSE
      - pint.json
      - README.md
      - '!.github/workflows/update-data.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  update-data:
    uses: typisttech/.github/.github/workflows/create-auto-merged-pull-request-php.yml@v2
    with:
      command: composer data:update
      php-version: '8.4'
      branch: "tastendruck/github_actions/update-data/${{ github.ref_name }}"
      labels: update_data
    secrets: inherit
